config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ('/')
  root 'kml_documents#index'

  resources :kml_documents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coordinate.rb
class Coordinate < ApplicationRecord
  belongs_to :geometry, polymorphic: true

  default_scope { order(:index) }

  def self.create_from_geojson(geometry, coordinate, index=nil)
    return self.create!(geometry: geometry, latitude: coordinate[1], longitude: coordinate[0], index: index)
  end
end

app/models/kml_document.rb
class KmlDocument < ApplicationRecord
  has_many :placemarks

  def self.create_from_geojson(geojson)
    kml_document = self.create!(name: geojson.original_filename)
    data = JSON.parse(File.read(geojson.tempfile)).with_indifferent_access

    if data[:type] == 'FeatureCollection'
      data[:features].each do |feature|
        kml_document.placemarks << Placemark.create_from_geojson(feature)
      end
    end

    return kml_document
  end
end

app/models/line_string.rb
class LineString < ApplicationRecord
  has_many :coordinates, as: :geometry
end

app/models/linear_ring.rb
class LinearRing < ApplicationRecord
  has_many :coordinates, as: :geometry

  def self.create_from_geojson(coordinates)
    linear_ring = self.create!()

    coordinates.each_with_index do |coordinate, i|
      Coordinate.create_from_geojson(linear_ring, coordinate, i)
    end

    return linear_ring
  end
end

app/models/multi_geometry.rb
class MultiGeometry < ApplicationRecord
end

app/models/placemark.rb
class Placemark < ApplicationRecord
  belongs_to :geometry, polymorphic: true

  def self.create_from_geojson(feature)
    placemark = self.new
    placemark.name = feature[:properties][:DisplayPlantName]
    placemark.description = "<h1>Properties:</h1><ul>#{feature[:properties].map { |k, v| "<li>#{k}: #{v}</li>" }.join}</ul>"

    case feature[:geometry][:type]
    when 'Point'
      placemark.geometry = Point.create_from_geojson(feature[:geometry])
    when 'Polygon'
      placemark.geometry = Polygon.create_from_geojson(feature[:geometry])
    when 'MultiPolygon'
      placemark.geometry = MultiPolygon.create_from_geojson(feature[:geometry])
    end

    placemark.save!
    return placemark
  end
end

app/models/point.rb
class Point < ApplicationRecord
  has_one :placemark, as: :geometry
  has_one :coordinate, as: :geometry

  def self.create_from_geojson(geometry)
    point = self.create!()
    Coordinate.create_from_geojson(point, geometry[:coordinates])
    return point
  end
end

app/models/polygon.rb
class Polygon < ApplicationRecord
  belongs_to :outer_boundary, class_name: 'LinearRing'
  has_many :polygon_inner_boundaries
  has_many :inner_boundaries, through: :polygon_inner_boundaries, source: 'linear_ring'

  def self.create_from_geojson(geometry)
    # First coordinate array is the outer boundary, remainder (if they exist) are the inner boundaries
    polygon = self.create!(outer_boundary: LinearRing.create_from_geojson(geometry[:coordinates].shift))
    polygon.inner_boundaries = geometry[:coordinates].map { |coordinate_array| LinearRing.create_from_geojson(coordinate_array) }
    return polygon
  end
end

app/models/polygon_inner_boundary.rb
class PolygonInnerBoundary < ApplicationRecord
  belongs_to :polygon
  belongs_to :linear_ring
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kml_documents_controller.rb
class KmlDocumentsController < ApplicationController
  def index
    @kml_documents = KmlDocument.all
  end

  def new
    @kml_document = KmlDocument.new
  end

  def create
    geojson = params.dig(:kml_document, :geojson)

    if geojson.present?
      KmlDocument.create_from_geojson(geojson)
      redirect_to(kml_documents_path)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @kml_document = KmlDocument.find_by(id: params[:id])
  end

  def show
    @kml_document = KmlDocument.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kml_documents_helper.rb
module KmlDocumentsHelper
end

app/views/kml_documents/_coordinate.html.erb
[<%= coordinate.latitude %>, <%= coordinate.longitude %>]

app/views/kml_documents/_linear_ring.html.erb
<ul>
  <li>Type: LinearRing</li>
  <li>Coordinates:
    <br>
    <% linear_ring.coordinates.each do |coordinate| %>
      <%= render(partial: 'coordinate', locals: { coordinate: coordinate }) %>
      <br>
    <% end %>
  </li>
</ul>

app/views/kml_documents/_placemark.html.erb
<ul>
  <li>Name: <%= placemark.name %></li>
  <li>Description: <%= placemark.description %></li>
  <li>Style Url: <%= placemark.style_url %></li>
  <li>Geometry: <%= render(partial: placemark.geometry_type.downcase, locals: { geometry: placemark.geometry }) %></li>
</ul>

app/views/kml_documents/_point.html.erb
<ul>
  <li>Type: Point</li>
  <li>Coordinate: <%= render(partial: 'coordinate', locals: { coordinate: geometry.coordinate }) %></li>
</ul>

app/views/kml_documents/_polygon.html.erb
<ul>
  <li>Type: Polygon</li>
  <li>Outer Boundary: <%= render(partial: 'linear_ring', locals: { linear_ring: geometry.outer_boundary }) %></li>
  <li>Inner Boundaries:
    <ul>
      <% geometry.inner_boundaries.each do |linear_ring| %>
        <li><%= render(partial: 'linear_ring', locals: { linear_ring: linear_ring }) %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/kml_documents/form.html.erb
<%= form_with model: @kml_document do |form| %>
  <div>
  <%= form.file_field(:geojson, accept: '.geojson') %>
  </div>
  <div>
  <%= form.submit %>
  </div>
<% end %>

app/views/kml_documents/index.html.erb
<h1>Kml Documents</h1>
<ul>
  <% @kml_documents.each do |doc| %>
    <li><%= link_to(doc.name, kml_document_path(doc)) %></li>
  <% end %>
</ul>

<%= link_to('New KML Document', new_kml_document_path) %>

app/views/kml_documents/new.html.erb
<%= form_with model: @kml_document do |form| %>
  <div>
  <%= form.file_field(:geojson, accept: '.geojson') %>
  </div>
  <div>
  <%= form.submit('Save') %>
  </div>
<% end %>

app/views/kml_documents/show.html.erb
<h1>Kml Document</h1>
<ul>
  <% @kml_document.placemarks.each do |placemark| %>
    <li>Placemark: <%= render(partial: 'placemark', locals: { placemark: placemark }) %></li>
  <% end %>
</ul>

<%= link_to('Back', kml_documents_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KmlEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>